[package]
name = "mcprs"
version = "0.1.0"
edition = "2024"
description = "MCP Router and Package manager"
authors = ["MCPRS Contributors"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "3.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
